### ISSUE TITLE
Issues.

### ISSUE THREAD

**Issue by ATouhou** [AdamGovier/Vue-3-Fast-Acting-Insulin-Calculator#2]
I just installed node.js (20.11.0 newest recommended version) and ran into some issues when trying to npm run build.  So many packages was outdated, so the following allowed me to build succcessfully: 

> 
> Follow these steps on your terminal in the current app directory:
> 
> npm install -g npm-check-updates
> Installs the npm-check-updates package globally for doing exactly what its name says.
> 
> ncu
> This will display the dependencies side-by-side with (an arrow pointing to) their new versions (you are advised to upgrade to) as listed in your package.json file in the current directory.
> 
> ncu -u
> This updates those new listed versions on your package.json file and prepares your app for the next step (the updates proper).
> 
> npm update
> or
> 
> npm install
> Either of these 2 finally installs the new updates; fixes the problem.

npm run serve  allows me to use the app in my browser. 
There are some errors however.
Creating a special time range for carb ratio doesen't work, here it is the apps "bad input" not allowing me to continue. However setting up a default works.

When trying to calculate bolus/insulin units: 
```
ERROR
Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at currentCarbRatio (webpack-internal:///./src/logic/scheduledCarbRatio.js:23:64)
    at carbs2Insulin (webpack-internal:///./src/logic/calculator.js:57:90)
    at calculate (webpack-internal:///./src/logic/calculator.js:17:37)
    at Proxy.runCalculations (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/Calculator.vue?vue&type=script&lang=js:99:88)
    at onClick._cache.<computed>._cache.<computed> (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/Calculator.vue?vue&type=template&id=19334bbc:124:59)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:336:18)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:344:17)
    at HTMLButtonElement.invoker (webpack-internal:///./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:835:82)
```

an error appears. 
Did you give up on this project?

**Comment by AdamGovier** [comment]
Hello, welcome! It is very nice to see that you have discovered my project.

I have been working full-time now for a while as a Software Developer and have unfortunately not had time to work on this project. I haven't "given up" I just have not worked on it in a long time.

So I believe I was developing this with Node.js V16 so a little older 😅. It would be worth getting the matching NPM version for V16 too. 

This works for me locally so if you still have issues after changing node version let me know.

Many thanks,
Adam

**Comment by AdamGovier** [comment]
Try building the original repo with Node 16 too please.

**Comment by AdamGovier** [comment]
I will test the scheduled carb ratio again - if you still have issues. But you will need to wait until I am back home which is not until mid February.

Thanks

**Comment by ATouhou** [comment]
No problem! My daughter was just diagnosed with diabetes type 1 as well. So I will make something super simple for her. Meanwhile I like to see what already exists, and your project seems to be one of the best available :) Both open-source and just in general ;) Good job :)

**Comment by ATouhou** [comment]
I'm sure project runs perfectly in the intended build environment. There are a lot of packages that are deprecated as JS / Browsers now supports it natively :)

**Comment by AdamGovier** [comment]
> No problem! My daughter was just diagnosed with diabetes type 1 as well. So I will make something super simple for her. Meanwhile I like to see what already exists, and your project seems to be one of the best available :) Both open-source and just in general ;) Good job :)

Yes - diabetes is very much a not one size fits all condition. I made this application as it works perfectly for me but I did want to share it with other diabetics. Feel free to adapt it to your needs :)

**Comment by AdamGovier** [comment]
https://github.com/AdamGovier/Vue-3-Fast-Acting-Insulin-Calculator/blob/master/src/logic/calculator.js

This file is the most important part. I would have a look at this if you want to make something simple :)

**Comment by ATouhou** [comment]
I think I would be most comfortable using your calculator as a validation tool. As medical decisions (how much insulin to administer) is decided by the app, I would feel more comfortable checking multiple different calculators results against each other.  I was in shock to see that this guy: https://github.com/mxklb/boluscalculator/issues/4  left both his app and code "live" even though multiple users reported calculation errors. (Happened at some point when some JS he was using was being parsed differently by the browser)

**Comment by ATouhou** [comment]
For now, Excel is my best friend 😆   I was shocked actually to see how poor options there are for diabetics in terms of software. Atleast I haven't found something that covers all the needs/simplifies everything. Dare I say, your app is the best available option I was able to track down? :)

**Comment by AdamGovier** [comment]
> For now, Excel is my best friend 😆   I was shocked actually to see how poor options there are for diabetics in terms of software. Atleast I haven't found something that covers all the needs/simplifies everything. Dare I say, your app is the best available option I was able to track down? :) 

Thanks for the feedback, for those reasons I need to write a lot of tests for this application but I haven't got round to it. That's why it isn't available for production :). Let's hope that the available closed source, paid software has robust code behind the scenes 😅.

**Comment by AdamGovier** [comment]
Again feel free to contribute. I have no intentions of making money from this software. So you will not only help the project but future users such as your daughter, me and many others with their condition.
